---
version: "3"

services:
  redis:
    image: redis:7.2.1-alpine
    networks:
      - qualentum
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 60s
      timeout: 5s
      retries: 2
    restart: unless-stopped


  app1:
    networks:
      - qualentum
    depends_on:
      redis:
        condition: service_healthy
    build: app1/
    ports:
      - "5000"

    deploy:
      restart_policy:
        condition: on-failure


  app2:
    networks:
      - qualentum
    depends_on:
      redis:
        condition: service_healthy
      app1:
        condition: service_started

    build: app2/
    ports:
      - "5000"

    deploy:
      restart_policy:
        condition: on-failure


  nginx:
    depends_on:
      redis:
        condition: service_healthy
      app1:
        condition: service_started
      app2:
        condition: service_started

    image: nginx:1.25.2-alpine
    container_name: loadbalancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"



networks:
  qualentum: {}
